controllers:
  resource: ../src/Controller/
  type: annotation

front_car_list:
  path: front/cars
  controller: App\Controller\Front\CarController::carList

front_car_show:
  path: front/car/{id}
  controller: App\Controller\Front\CarController::carShow

update_car:
  path: admin/update/car/{id}
  controller: App\Controller\Admin\CarController::carUpdate

create_car:
  path: admin/create/car
  controller: App\Controller\Admin\CarController::createCar

delete_car:
  path: admin/delete/car/{id}
  controller: App\Controller\Admin\CarController::deleteCar

front_search:
  path: search
  controller: App\Controller\Front\CarController::frontSearch

front_brand_list:
  path: front/brands
  controller: App\Controller\Front\BrandController::brandList 

front_brand_show:
  path: front/brand
  controller: App\Controller\Front\BrandController::brandShow 

create_brand:
  path: admin/create/brand
  controller: App\Controller\Admin\BrandController::createBrand 

update_brand:
  path: admin/update/brand/{id}
  controller: App\Controller\Admin\BrandController::brandUpdate

delete_brand:
  path: admin/delete/brand/{id}
  controller: App\Controller\Admin\BrandController::deleteGoup  

front_group_list:
  path: front/groups
  controller: App\Controller\Front\GroupController::groupList 

front_group_show:
  path: front/group
  controller: App\Controller\Front\GroupController::groupShow 

create_group:
  path: admin/create/group
  controller: App\Controller\Admin\GroupController::createGroup

update_group:
  path: admin/update/group/{id}
  controller: App\Controller\Admin\GroupController::groupUpdate 

delete_group:
  path: admin/delete/group/{id}
  controller: App\Controller\Admin\GroupController::deleteGroup

create_image:
  path: admin/create/image
  controller: App\Controller\Admin\ImageController::createImage



kernel:
  resource: ../src/Kernel.php
  type: annotation
